#!/usr/bin/env sh
set -eu #o pipefail

[ "$(hostname)" != archiso ] && exit

CHECK() {
	# "local" is not POSIX-compliant
	echo "$1"
	echo "Proceed? [Y/n]"
	read -r ans </dev/tty
	[ "$ans" = n ] && exit 1
	unset ans
}

# https://wiki.archlinux.org/title/Installation_guide

# ls /usr/share/kbd/keymaps/**/*.map.gz
# loadkeys LAYOUT

if ls /sys/firmware/efi/efivars; then
	MODE=UEFI
	echo "UEFI mode"
else
	MODE=BIOS
	echo "BIOS mode"
fi

ip link

# https://wiki.archlinux.org/title/Iwd#Connect_to_a_network
# TODO:
# iwctl --passphrase [passphrase] station [device] connect [SSID]
until ping archlinux.org; do iwctl; done

timedatectl set-ntp true

fdisk -l

# typical windows scenario
# sda1: 50 MB (HPFS/NTFS/exFAT)
# sda2: most of the disk
# sda3: 500 MB (Hidden NTFS WinRE)

# RAM should be measured in gigs
RAM=$(free -g | awk '/Mem/ {print $2}')
RAM=$((RAM + 1))

# backup partition table
# sfdisk -d /dev/sda > sda.dump

# BIOS mode is used, root and 8GB swap (no home)
# this is obviously a hacky way to automate fdisk; use at your own risk!
# https://wiki.archlinux.org/title/Partitioning#Partitioning_tools
# https://gist.github.com/tuxfight3r/c640ab9d8eb3806a22b989581bcbed43
# https://www.thegeekstuff.com/2017/05/sfdisk-examples/

# lsblk | grep 'sd. ' | grep -v T | cut -d' ' -f1
DEV=/dev/sda

fdisk "$DEV" <<EOF
n
p
1

-${RAM}G
n
p
2


t
2
82
p
w
EOF

lsblk
fdisk -l | grep "$DEV"
CHECK "Wrote partition table"

mkfs.ext4 "${DEV}1"
mkswap "${DEV}2"

mount "${DEV}1" /mnt
swapon "${DEV}2"

reflector

pacstrap /mnt base linux linux-firmware vim git networkmanager

genfstab -U /mnt >>/mnt/etc/fstab

arch-chroot /mnt

# idk if it'll work from this point on

ln -sf /usr/share/zoneinfo/Europe/Berlin /etc/localtime
hwclock --systohc

locale-gen
sed -i -r '/#en_US/ s|#||' /etc/locale.gen

echo "LANG=en_US.UTF-8" >/etc/locale.conf

# probably won't need most of these, but these were generated by manjaro
# LANG=en_US.UTF-8
# LC_ADDRESS=en_GB.UTF-8
# LC_IDENTIFICATION=en_GB.UTF-8
# LC_MEASUREMENT=en_GB.UTF-8
# LC_MONETARY=en_GB.UTF-8
# LC_NAME=en_GB.UTF-8
# LC_NUMERIC=en_GB.UTF-8
# LC_PAPER=en_GB.UTF-8
# LC_TELEPHONE=en_GB.UTF-8
# LC_TIME=en_GB.UTF-8

HOSTNAME=joseph

echo $HOSTNAME >/etc/hostname

# localdomain has been omitted
cat <<EOF >/etc/hosts
127.0.0.1  localhost
::1        localhost
127.0.1.1  $HOSTNAME
EOF

# Net
# nmtui

passwd

# maybe not in chroot
# systemctl start NetworkManager.service
# systemctl enable NetworkManager.service

pacman -S grub

exit

umount -R /mnt

echo "Rebooting in 5 seconds..."

sleep 5

reboot now
