#!/usr/bin/env sh
set -eu

# configure services, network, graphical environment, git credentials in the
# newly installed OS.

if [ "$(whoami)" = root ]; then
	echo "This script is not to be run as root!"
	exit
fi

systemctl status NetworkManager.service | grep running || {
	sudo systemctl start NetworkManager.service
	sudo systemctl enable NetworkManager.service
}

ping -c 1 archlinux.org || sudo nmtui

# replace the mirrors from reflector since they're not very good

country=$(curl -sL "https://ipinfo.io" | jq -r .country)
curl -s "https://archlinux.org/mirrorlist/?country=$country&protocol=https&ip_version=4&ip_version=6" |
	sed -r 's|^#Server|Server|' |
	sudo tee /etc/pacman.d/mirrorlist

sudo pacman -Syu

# https://www.davidtsadler.com/posts/installing-st-dmenu-and-dwm-in-arch-linux/
sudo pacman -S base-devel libx11 libxft xorg-server xorg-xinit terminus-font libxinerama kitty ranger firefox chromium

setup_git_ssh() { # {{{
	# without ssh, you cannot clone -any- repo. but with ssh, you can clone
	# public and private repos.

	# https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent#generating-a-new-ssh-key
	# https://docs.github.com/en/authentication/connecting-to-github-with-ssh/adding-a-new-ssh-key-to-your-github-account#adding-a-new-ssh-key-to-your-account

	# https://cli.github.com/manual/gh_auth_login

	ssh_key_name=github_$(date -I)

	if [ ! -f ~/.ssh/"$ssh_key_name" ]; then
		mkdir -p ~/.ssh
		# no long options :(
		ssh-keygen -f ~/.ssh/"$ssh_key_name" -t ed25519 -C "hejops1@gmail.com"
	fi

	# # should be done on every login (xinitrc)
	# {
	# 	eval "$(ssh-agent -s)"
	# 	ssh-add ~/.ssh/"$ssh_key_name"
	# } > /dev/null 2> /dev/null

	# https://cli.github.com/manual/gh_auth_login

	if [ ! -d ~/.config/gh ]; then
		chromium --incognito &
		gh auth login
	fi

	machine="$(cat /sys/devices/virtual/dmi/id/product_name)"
	if ! gh ssh-key list | grep -q "$machine"; then
		gh auth refresh --hostname github.com --scopes admin:public_key
		gh auth refresh --hostname github.com --scopes admin:ssh_signing_key
		gh ssh-key add --title "${machine}_$(date -I)" ~/.ssh/"$ssh_key_name".pub
	fi
} # }}}
setup_git_ssh

cd
git clone https://github.com/hejops/dwm
cd dwm
make clean
sudo make install

cat << EOF > "$HOME/.xinitrc"
# vim: ft=sh
# auto-generated by $(basename "$0")
setxkbmap -layout us -option -option compose:rctrl #,caps:menu
xrdb -merge ~/.Xresources

source ~/.bashrc

if [[ -z \$SSH_AUTH_SOCK ]]; then
	{
		pkill ssh-agent
		eval "\$(ssh-agent -s)"
		find ~/.ssh | grep github | grep -v pub | xargs ssh-add
	} > /dev/null 2> /dev/null
fi

exec dwm
EOF

# https://wiki.archlinux.org/title/Xinit#Autostart_X_at_login
# https://unix.stackexchange.com/a/521049
# apparently, .bash_profile is tried by default, while .profile is totally ignored

cat << EOF > "$HOME/.bash_profile"
if [ "\$DISPLAY" = "" ] && [ "\$XDG_VTNR" -eq 1 ]; then
	exec startx
fi
EOF

sudo sed -i -r 's/#SystemMaxUse.+/SystemMaxUse=100M/' /etc/systemd/journald.conf

cat << EOF
Successfully configured dwm
dwm will be started automatically after logging back in
EOF

# pkill bash
